### ISSUE TITLE
Freezes during boot after editing /etc/default/grub

### ISSUE THREAD

**Issue by averagenokiauser** [jmstriegel/linux_2006_imac_5.1#2]
After i edited GRUB_CMDLINE_LINUX_DEFAULT and restarted my iMac it just freezes on a black screen. I tried booting it without quiet boot parameter and it freezes at the line 3.039716] fb0: switching to radeondrmfb from EFI VGA. Any idea how i can fix this?
![IMG_1711](https://github.com/user-attachments/assets/e5295d7e-6dfe-4d15-aa0f-34d7208c5b6e)

**Comment by jmstriegel** [comment]
Sorry for the late reply. You might try using the nomodeset boot parameter to get things running first without GPU acceleration. That should at least get you booted (assuming its a video issue), and you can install any driver updates and debug things from there.

**Comment by averagenokiauser** [comment]
The issue was that it didn’t install in legacy mode.
